controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    joint_trajectory_controller:
      type: effort_controllers/JointGroupEffortController
    
    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints:
      - Revolute_1
      - Revolute_3
      - Revolute_4
      - Revolute_5
      - Revolute_20
      - Revolute_23
      - Revolute_25
      - Revolute_40
      - Revolute_31
      - Revolute_48
      - Revolute_35
      - Revolute_45
     gains:
        Revolute_1: {p: 100, i: 0.1, d: 10}
        Revolute_3: {p: 100, i: 0.1, d: 10}
        Revolute_4: {p: 100, i: 0.1, d: 10}
        Revolute_5: {p: 100, i: 0.1, d: 10}
        Revolute_20: {p: 100, i: 0.1, d: 10}
        Revolute_23: {p: 100, i: 0.1, d: 10}
        Revolute_25: {p: 100, i: 0.1, d: 10}
        Revolute_40: {p: 100, i: 0.1, d: 10}
        Revolute_31: {p: 100, i: 0.1, d: 10}
        Revolute_48: {p: 100, i: 0.1, d: 10}
        Revolute_35: {p: 100, i: 0.1, d: 10}
        Revolute_45: {p: 100, i: 0.1, d: 10}


