controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    joint_trajectory_controller:
      type: position_controllers/JointGroupPositionController
    
    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints:
      - Revolute_1
      - Revolute_3
      - Revolute_4
      - Revolute_5
      - Revolute_20
      - Revolute_23
      - Revolute_25
      - Revolute_40
      - Revolute_31
      - Revolute_48
      - Revolute_35
      - Revolute_45


